title: '新世纪韭菜的博客'
description: '......'
keyword: 'android, react-native, flutter, cordova'
url: ''
baseurl: ''

nav:
  home: '/'
  tags: '/tags.html'

footer:
  since: 2016

author: '新世纪韭菜'
bio: '移动端开发者'
avatar: '/assets/img/profile.jpeg'

search: true

nightMode: true

mathjax: true

theme-color: 'pink'

postPatterns: 'circuitBoard'

sns:
  zhihu: '//zhihu.com/people/feiq/activities'
  github: '//github.com/7449'

recommend-tags: true
recommend-condition-size: 12

paginate: 20
paginate_path: 'page:num'
exclude: ['.gitignore', 'README.md']

markdown: kramdown
kramdown:
  input: GFM
permalink: /:year/:month/:day/:title

plugins: [jekyll-paginate]

ba_track_id: 5edf92f51848209f68f95c841d40a5f0
